services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=proj_mgmt_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=S3cret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
